# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f270312bec92a8c8292999db55d9d8f20f06f819e70d05ea32b5a677ac906929750c5fca911c998542e1a7a2588c0257237a89e76c570a7547a0e152e843133c

test:
  secret_key_base: d9da6201983dcd7956c6a977d9816431a3e30379d63efb5fc8a96007694046ae3c19b129f76ad58dea6fe8fccdac2a2c65a51c9c6245e8591d5679cb12b60d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
